archlinux basic adaptation
d2learn/xim-pkgindex pull request #6
Opened 2024-12-16 14:56 UTC by MoYingJi

pmwrapper: mdboox, rustup, vim

2024-12-19 14:35 UTC, Sunrisepeak commented
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nvm
如果使用nvm安装nodejs会对pacman有什么影响吗, 并没有看到 nvm在node上对pacman有特殊处理好像

2024-12-20 13:46 UTC, MoYingJi commented
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nvm 如果使用nvm安装nodejs会对pacman有什么影响吗, 并没有看到 nvm在node上对pacman有特殊处理好像

我没试过 我装了一下好像并没有什么影响 nvm nodejs pnpm 正常共存

2024-12-21 09:26 UTC, Sunrisepeak commented
> > https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nvm 如果使用nvm安装nodejs会对pacman有什么影响吗, 并没有看到 nvm在node上对pacman有特殊处理好像
> 
> 我没试过 我装了一下好像并没有什么影响 nvm nodejs pnpm 正常共存

为什么, nvm 不通过pacman安装不会有 "依赖问题", 如果使用 xlings install nodejs 会有依赖问题吗, 感觉需要找到这里面的核心原因 然后想办法怎么能让通过xlings安装 做到尽量不影响pacman, 等会我也装个arch分析一下安装过程 和 pacman的数据库

2024-12-21 09:28 UTC, Sunrisepeak commented
感觉核心应该是 pacman的数据库中记录的信息 已经 数据库信息的 增加和删除

2024-12-22 10:15 UTC, Sunrisepeak requested changes
pmwrapper 和 xpkg-pkgs 是可以共存的 mdbook/nodejs/pnpm里的archlinux支持可以不用删除。具体安装的方式可以交给用户选择

2024-12-22 10:15 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +        archlinux = {
xpm可以自动clone仓库, https://aur.archlinux.org/nvm.git

2024-12-22 10:15 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +    else if is_host("linux") and utils.os_info().name == "archlinux" then
这里可以直接判断os_info, 前面的is_host("linux")可以省去

2024-12-22 10:15 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +        os.execv("makepkg", {"-si"})
这里同上, xpm自动会把仓库clone到当前目录。这里应该cd到仓库目录然后 makepkg应该就可以了(可能需要本地验证

2024-12-22 10:15 UTC, Sunrisepeak commented on pmwrapper.lua
> +    ["mdbook"] = {
这个文件的kv后都加一个, 避免下次添加其他系统支持时出错的可能性

2024-12-22 10:22 UTC, Sunrisepeak commented
@MoYingJi  现在xim支持对单包文件进行测试了, 可以在本地测试一下nvm能不能在archlinux上正常安装卸载

(现在os_info.name 的信息 其实还不能确定是不是 'archlinux' 还是 ‘arch linux’)

![image](https://github.com/user-attachments/assets/04ca05ed-6653-4ecb-b2f0-32a49625bcde)

2024-12-22 10:27 UTC, Sunrisepeak commented
安装通过 pacman的话, 卸载应该也需要 对于nvm 
![image](https://github.com/user-attachments/assets/c47e9049-a999-4be3-a69d-fb217e496912)

2024-12-22 15:23 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +            ["latest"] = {
如果只有latest版本, 现在本地安装应该会失败。需要在installed函数中特殊处理archlinux上nvm是否安装, 通过返回true 或 false来判定。如果返回 nvm --version 输出的字符串的话 并不包含 latest 这个版本的字符串在里面。可以通过判定 os_info.name 然后 特殊处理archlinux上是否被安装的判定 (如判定nvm --version命令是否执行为依据 或 os.iorun("nvm --version") ~= nil)

2024-12-22 15:26 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +            ["latest"] = {
其实按理 archlinux = { ref = "ubuntu" } 应该也是支持的, nvm的安装脚本应该支持多个linux发行版本

2024-12-28 06:49 UTC, Sunrisepeak requested changes

2024-12-28 06:49 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +if [ "$NVM_DIR" == "" ]; then export NVM_DIR="$HOME/.nvm"; end
这里end的结束语法有问题。 直接覆盖性质是一样的 append_bashrc 函数中 有字符串检测 如果已经设置过了不会重复设置

2024-12-28 06:49 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +    elseif utils.os_info().name == "archlinux" then
这个可以放到aur的pmwrapper中 [#61](https://github.com/d2learn/xlings/issues/61)

2024-12-28 08:02 UTC, MoYingJi commented on pkgs/n/nvm.lua
> +if [ "$NVM_DIR" == "" ]; then export NVM_DIR="$HOME/.nvm"; end
> 直接覆盖性质是一样的 append_bashrc 函数中 有字符串检测 如果已经设置过了不会重复设置
![图片](https://github.com/user-attachments/assets/b93b4e1a-b337-4b87-9dfa-6c8bff3f2de6)
问题是 这是根据内容进行字符串检测 应该要完全匹配？
如果用户手动加了 NVM_DIR=xxx 那么也会加一遍
或者用户在其他 profile 文件中添加了 也不会被检测到

2024-12-28 08:14 UTC, Sunrisepeak commented on pkgs/n/nvm.lua
> +if [ "$NVM_DIR" == "" ]; then export NVM_DIR="$HOME/.nvm"; end
这里如果用户自己添加了nvm_dir可能路径并不可控, 或者说nvm已经被安装了 这个时候应该不会再安装才对。
如果在安装的情况下, 依然使用xim进行安装, 应该进行覆盖保证xim安装的版本是可用的

2024-12-28 08:30 UTC, MoYingJi commented on pkgs/n/nvm.lua
> +if [ "$NVM_DIR" == "" ]; then export NVM_DIR="$HOME/.nvm"; end
我感觉那也要留给用户配置的空间吧 arch里nvm的init-nvm.sh也是有这个if判断的 而不是就写死了
如果没有if判断用户是否配置NVM_DIR的话 用户想改路径只能在bashrc里自动添加的下面覆盖了

2024-12-28 08:50 UTC, Sunrisepeak approved these changes

2024-12-28 08:50 UTC, merged